export const categories = [
  { id: 'rice', name: 'จานข้าว' },
  { id: 'noodle', name: 'เส้น' },
  { id: 'soup', name: 'ต้ม / แกง' },
  { id: 'side', name: 'กินเล่น' },
  { id: 'drink', name: 'เครื่องดื่ม' },
];

export const menu = [
  { id: 'r1', category: 'rice', name: 'ข้าวกะเพราหมูสับ', price: 65, icon: '🍛' },
  { id: 'r2', category: 'rice', name: 'ข้าวผัดกุ้ง', price: 75, icon: '🍤' },
  { id: 'r3', category: 'rice', name: 'ข้าวมันไก่', price: 60, icon: '🍚' },
  { id: 'r4', category: 'rice', name: 'ข้าวหมูทอดกระเทียม', price: 65, icon: '🍖' },
  { id: 'r5', category: 'rice', name: 'ข้าวไข่ข้น', price: 55, icon: '🍳' },
  { id: 'n1', category: 'noodle', name: 'ผัดไทยกุ้งสด', price: 80, icon: '🍜' },
  { id: 'n2', category: 'noodle', name: 'ก๋วยเตี๋ยวหมูน้ำใส', price: 60, icon: '🍜' },
  { id: 'n3', category: 'noodle', name: 'ราดหน้าหมู', price: 65, icon: '🍲' },
  { id: 'n4', category: 'noodle', name: 'ผัดซีอิ๊วไก่', price: 65, icon: '🍝' },
  { id: 'n5', category: 'noodle', name: 'สปาเกตตีขี้เมา', price: 85, icon: '🍝' },
  { id: 's1', category: 'soup', name: 'ต้มยำกุ้ง', price: 120, icon: '🍲' },
  { id: 's2', category: 'soup', name: 'ต้มข่าไก่', price: 95, icon: '🥣' },
  { id: 's3', category: 'soup', name: 'แกงเขียวหวานไก่', price: 100, icon: '🍛' },
  { id: 's4', category: 'soup', name: 'แกงจืดเต้าหู้หมูสับ', price: 85, icon: '🥣' },
  { id: 's5', category: 'soup', name: 'พะแนงหมู', price: 105, icon: '🍲' },
  { id: 'a1', category: 'side', name: 'ปีกไก่ทอด', price: 75, icon: '🍗' },
  { id: 'a2', category: 'side', name: 'เฟรนช์ฟรายส์', price: 65, icon: '🍟' },
  { id: 'a3', category: 'side', name: 'ทอดมันปลา', price: 80, icon: '🍥' },
  { id: 'a4', category: 'side', name: 'ส้มตำไทย', price: 60, icon: '🥗' },
  { id: 'a5', category: 'side', name: 'ยำวุ้นเส้น', price: 85, icon: '🥗' },
  { id: 'd1', category: 'drink', name: 'น้ำเปล่า', price: 15, icon: '💧' },
  { id: 'd2', category: 'drink', name: 'ชาไทยเย็น', price: 45, icon: '🧋' },
  { id: 'd3', category: 'drink', name: 'กาแฟเย็น', price: 50, icon: '☕' },
  { id: 'd4', category: 'drink', name: 'น้ำมะนาว', price: 45, icon: '🍋' },
  { id: 'd5', category: 'drink', name: 'น้ำอัญชันมะนาว', price: 50, icon: '🍹' },
];
