import { StyleSheet } from 'react-native';

export const colors = { bg: '#F8F5EF', card: '#FFFDF9', text: '#3E352D', muted: '#81766B', border: '#E9E0D5', green: '#52745C', pale: '#E7EFE7', peach: '#FFF3E7' };
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg }, body: { flex: 1 },
  header: { paddingHorizontal: 22, paddingTop: 25, paddingBottom: 17 },
  brand: { color: colors.green, fontSize: 11, fontWeight: '700', letterSpacing: 2, marginBottom: 10 },
  title: { color: colors.text, fontSize: 28, fontWeight: '700' }, subtitle: { color: colors.muted, fontSize: 14, marginTop: 4 },
  legend: { flexDirection: 'row', gap: 17, paddingHorizontal: 22, marginBottom: 10 },
  legendText: { color: colors.green, fontSize: 12 }, busyText: { color: '#AB744E' },
  tableList: { paddingHorizontal: 15, paddingBottom: 16 },
  table: { flex: 1, height: 110, margin: 6, borderWidth: 1, borderColor: colors.border, borderRadius: 17, backgroundColor: colors.card, alignItems: 'center', justifyContent: 'center' },
  busyTable: { backgroundColor: colors.peach, borderColor: '#E8C9A8' },
  tableIcon: { color: colors.green, fontSize: 24, lineHeight: 27 },
  tableName: { color: colors.text, fontSize: 16, fontWeight: '700', marginTop: 2 },
  tableStatus: { color: colors.green, fontSize: 12, marginTop: 4 },
  categoryScroll: { flexGrow: 0 }, categories: { paddingHorizontal: 20, paddingBottom: 14, gap: 8 },
  chip: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 20, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  activeChip: { backgroundColor: colors.green, borderColor: colors.green },
  chipText: { color: colors.muted, fontSize: 14 }, activeChipText: { color: 'white', fontWeight: '700' },
  list: { paddingHorizontal: 20, paddingBottom: 20 },
  menuCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 12, marginBottom: 10 },
  foodIcon: { width: 52, height: 52, backgroundColor: '#F4EDE3', borderRadius: 13, textAlign: 'center', textAlignVertical: 'center', fontSize: 25, overflow: 'hidden' },
  foodInfo: { flex: 1, paddingHorizontal: 12 }, foodName: { color: colors.text, fontSize: 15, fontWeight: '600' },
  price: { color: colors.green, fontSize: 14, marginTop: 4 },
  add: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' },
  addText: { color: 'white', fontSize: 23, lineHeight: 27 },
  footer: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 8, borderTopWidth: 1, borderTopColor: colors.border },
  button: { minHeight: 48, borderRadius: 13, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' },
  buttonText: { color: 'white', fontSize: 15, fontWeight: '700' },
  secondaryButton: { backgroundColor: 'transparent', minHeight: 39 }, secondaryText: { color: colors.green, fontSize: 14 },
  disabled: { opacity: 0.45 }, empty: { color: colors.muted, textAlign: 'center', marginTop: 75, fontSize: 15 },
  card: { backgroundColor: colors.card, borderRadius: 15, padding: 15, borderWidth: 1, borderColor: colors.border, marginBottom: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  itemName: { flex: 1, color: colors.text, fontSize: 15, fontWeight: '700' }, amount: { color: colors.text, fontSize: 14, fontWeight: '600' },
  quantityRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  quantityButton: { width: 30, height: 30, borderRadius: 8, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' },
  quantitySymbol: { color: colors.green, fontSize: 20 }, quantity: { color: colors.text, minWidth: 34, textAlign: 'center', fontSize: 15 },
  unitPrice: { color: colors.muted, fontSize: 12, marginLeft: 10 },
  input: { backgroundColor: '#FAF7F1', borderRadius: 9, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, paddingVertical: 9, marginTop: 12, color: colors.text, fontSize: 14 },
  totalLabel: { color: colors.text, fontSize: 16 }, total: { color: colors.green, fontSize: 18, fontWeight: '700' },
  roundTitle: { color: colors.green, fontSize: 16, fontWeight: '700', marginBottom: 7 },
  billRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingVertical: 6 },
  billName: { flex: 1, color: colors.text, fontSize: 14 },
  kitchenMeta: { color: colors.green, fontSize: 12, fontWeight: '600' },
  kitchenName: { color: colors.text, fontSize: 17, fontWeight: '700', marginTop: 7 },
  note: { color: colors.muted, fontSize: 13, marginTop: 4 },
  statusRow: { flexDirection: 'row', gap: 6, marginTop: 13 },
  statusChip: { flex: 1, paddingVertical: 8, borderRadius: 9, backgroundColor: '#F4F0E9', alignItems: 'center' },
  activeStatus: { backgroundColor: colors.pale }, statusText: { color: colors.muted, fontSize: 11 },
  activeStatusText: { color: colors.green, fontWeight: '700' },
  tabs: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.card, paddingVertical: 8 },
  tab: { flex: 1, alignItems: 'center', paddingVertical: 8 }, tabText: { color: colors.muted, fontSize: 13 },
  activeTab: { color: colors.green, fontWeight: '700' },
});
